# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='topic',
            new_name='topics',
        ),
    ]
