# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180313_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askanswers',
            old_name='answers',
            new_name='answer_title',
        ),
        migrations.AddField(
            model_name='askanswers',
            name='answer_detail',
            field=models.TextField(default='', max_length=500, verbose_name='详细回答'),
        ),
    ]
