# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20180317_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='askanswers',
            name='answer_reply',
            field=models.TextField(default='', max_length=200, null=True, verbose_name='回复'),
        ),
    ]
