# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-17 16:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0004_askanswers_answer_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_reply', models.TextField(default='', max_length=200, null=True, verbose_name='回复')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '问题回答',
                'verbose_name_plural': '问题回答',
            },
        ),
        migrations.RemoveField(
            model_name='askanswers',
            name='answer_reply',
        ),
        migrations.AddField(
            model_name='answersreply',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.AskAnswers', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='answersreply',
            name='ask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Ask', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='answersreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
