# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-17 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180318_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersreply',
            options={'verbose_name': '回答回复', 'verbose_name_plural': '回答回复'},
        ),
    ]
