# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askanswers',
            name='ask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Ask', verbose_name='问题'),
        ),
    ]
