# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.IntegerField(null=True, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='register_time',
            field=models.DateField(blank=True, null=True, verbose_name='注册时间'),
        ),
    ]
