# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-19 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '站内消息', 'verbose_name_plural': '站内消息'},
        ),
    ]
